replicaCount: 1

image:
  repository: prithivkrishna/front-end
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

nameOverride: ""
fullnameOverride: "front-end"


service:
  type: ClusterIP
  port: 80

config:
  REACT_APP_API_URL: "http://localhost:5039"


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
