replicaCount: 1

image:
  repository: prithivkrishna/payments-api
  pullPolicy: IfNotPresent
  tag: "v1.0.0"


nameOverride: ""
fullnameOverride: "payments-api"

service:
  type: ClusterIP
  port: 5039

containerPort: 80

livenessProbe:
  httpGet:
    path: /api/payments
    port: http
readinessProbe:
  httpGet:
    path: /api/payments
    port: http
